# Generated by Django 5.0.6 on 2025-11-09 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En proceso'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=40)),
                ('categoria', models.CharField(choices=[('HERENCIA', 'Herencia'), ('DEMANDA_CIVIL', 'Demanda civil'), ('JUICIO_LABORAL', 'Juicio laboral'), ('CONTRATO', 'Contrato'), ('ASESORIA', 'Asesoría'), ('OTROS', 'Otros')], db_index=True, default='OTROS', max_length=40)),
                ('codigo_caso', models.CharField(editable=False, max_length=20, unique=True)),
                ('drive_folder_id', models.CharField(blank=True, max_length=128, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('abogado_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_responsables', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='clients.cliente')),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=128, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(blank=True, max_length=255)),
                ('tamano', models.BigIntegerField(blank=True, null=True)),
                ('modificado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='cases.caso')),
            ],
            options={
                'verbose_name': 'Archivo de Caso',
                'verbose_name_plural': 'Archivos de Casos',
                'ordering': ['-modificado_en', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('subido', 'Subido'), ('descargado', 'Descargado'), ('visto', 'Visto'), ('sincronizado', 'Sincronizado')], max_length=40)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='cases.archivocaso')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_archivo', to=settings.AUTH_USER_MODEL)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='cases.caso')),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['caso', '-creado_en'], name='cases_archi_caso_id_2de1a7_idx'), models.Index(fields=['accion', '-creado_en'], name='cases_archi_accion_4f79de_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccesoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_editar', models.BooleanField(default=False)),
                ('abogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_casos', to=settings.AUTH_USER_MODEL)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='cases.caso')),
            ],
            options={
                'verbose_name': 'Acceso a Caso',
                'verbose_name_plural': 'Accesos a Casos',
                'unique_together': {('caso', 'abogado')},
            },
        ),
    ]
