# Generated by Django 5.0.6 on 2025-10-15 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_CURSO', 'En curso'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('abogado_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos_responsable', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='clients.cliente')),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='AccesoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_editar', models.BooleanField(default=False)),
                ('abogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_caso', to=settings.AUTH_USER_MODEL)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='cases.caso')),
            ],
            options={
                'verbose_name': 'Acceso a caso',
                'verbose_name_plural': 'Accesos a casos',
                'unique_together': {('caso', 'abogado')},
            },
        ),
    ]
