# Generated by Django 5.0.6 on 2025-10-16 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_caso_prioridad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesocaso',
            options={'verbose_name': 'Acceso a Caso', 'verbose_name_plural': 'Accesos a Casos'},
        ),
        migrations.RemoveField(
            model_name='caso',
            name='prioridad',
        ),
        migrations.AddField(
            model_name='caso',
            name='codigo_caso',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='accesocaso',
            name='abogado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_casos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caso',
            name='abogado_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_responsables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caso',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En proceso'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='caso',
            name='titulo',
            field=models.CharField(max_length=180),
        ),
    ]
