# Generated by Django 5.0.6 on 2025-10-18 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_alter_caso_codigo_caso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=128, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(blank=True, max_length=255)),
                ('tamano', models.BigIntegerField(blank=True, null=True)),
                ('modificado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='cases.caso')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo de Caso',
                'verbose_name_plural': 'Archivos de Casos',
                'ordering': ['-modificado_en', '-creado_en'],
            },
        ),
    ]
