# Generated by Django 5.0.6 on 2025-10-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_archivocaso'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
