# Generated by Django 5.0.6 on 2025-10-18 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_caso_drive_folder_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('subido', 'Subido'), ('descargado', 'Descargado'), ('visto', 'Visto'), ('sincronizado', 'Sincronizado')], max_length=20)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='cases.archivocaso')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='cases.caso')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_archivo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['caso', '-creado_en'], name='cases_archi_caso_id_2de1a7_idx'), models.Index(fields=['accion', '-creado_en'], name='cases_archi_accion_4f79de_idx')],
            },
        ),
    ]
