# Generated by Django 5.0.6 on 2025-10-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_caso_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='categoria',
            field=models.CharField(choices=[('HERENCIA', 'Herencia'), ('DEMANDA_CIVIL', 'Demanda civil'), ('JUICIO_LABORAL', 'Juicio laboral'), ('CONTRATO', 'Contrato'), ('ASESORIA', 'Asesoría'), ('OTROS', 'Otros')], db_index=True, default='OTROS', max_length=40),
        ),
    ]
