# Generated by Django 5.0.6 on 2025-10-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_alter_caso_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoevento',
            name='accion',
            field=models.CharField(choices=[('subido', 'Subido'), ('descargado', 'Descargado'), ('visto', 'Visto'), ('sincronizado', 'Sincronizado')], max_length=40),
        ),
        migrations.AlterField(
            model_name='caso',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En proceso'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=40),
        ),
    ]
