# Generated by Django 5.0.6 on 2025-10-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
