# Generated by Django 5.0.6 on 2025-11-09 23:41

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'Ya existe un usuario con ese nombre de usuario.'}, help_text='Requerido. 150 caracteres o menos. Solo letras, números y los símbolos @ . + - _', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras, números y los símbolos @ . + - _', regex='^[\\w.@+-]+$')], verbose_name='Nombre de usuario')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('ABOGADO', 'Abogado'), ('DESHABILITADO', 'Deshabilitado')], default='ABOGADO', help_text='Define el rol del usuario dentro del sistema (Administrador, Abogado o Deshabilitado).', max_length=20, verbose_name='Rol')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si este usuario puede iniciar sesión. Desmarca esta opción en lugar de eliminar la cuenta.', verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, help_text='Permite que el usuario acceda al panel de administración de Django.', verbose_name='Acceso al panel de administración')),
                ('is_superuser', models.BooleanField(default=False, help_text='Otorga todos los permisos sin necesidad de asignarlos explícitamente.', verbose_name='Superusuario')),
                ('email', models.EmailField(blank=True, help_text='Dirección de correo electrónico de contacto del usuario.', max_length=254, verbose_name='Correo electrónico')),
                ('first_name', models.CharField(blank=True, help_text='Nombre del usuario.', max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, help_text='Apellidos del usuario.', max_length=150, verbose_name='Apellidos')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GoogleCalendarCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials_json', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gcal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials_json', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
