# Generated by Django 5.0.6 on 2025-11-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usuario_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, help_text='Dirección de correo electrónico de contacto del usuario.', max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(blank=True, help_text='Nombre del usuario.', max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si este usuario puede iniciar sesión. Desmarca esta opción en lugar de eliminar la cuenta.', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Permite que el usuario acceda al panel de administración de Django.', verbose_name='Acceso al panel de administración'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Otorga todos los permisos sin necesidad de asignarlos explícitamente.', verbose_name='Superusuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(blank=True, help_text='Apellidos del usuario.', max_length=150, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('ABOGADO', 'Abogado'), ('DESHABILITADO', 'Deshabilitado')], default='ABOGADO', help_text='Define el rol del usuario dentro del sistema (Administrador, Abogado o Deshabilitado).', max_length=20, verbose_name='Rol'),
        ),
    ]
