# Generated by Django 5.0.6 on 2025-11-07 04:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usuario_email_alter_usuario_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con ese nombre de usuario.'}, help_text='Requerido. 150 caracteres o menos. Solo letras, números y los símbolos @ . + - _', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras, números y los símbolos @ . + - _', regex='^[\\w.@+-]+$')], verbose_name='Nombre de usuario'),
        ),
    ]
